import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
config :emoji, EmojiWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "emojigen.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: ["https://emojigen.com", "https://www.emojigen.com", "https://emoji.fly.dev"]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :emoji, EmojiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Emoji.Finch

# Do not print debug messages in production
config :logger, level: :info

config :emoji, env: :prod

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
