import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :sticker, StickerWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "stickerbaker.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://stickerbaker.com",
    "https://www.stickerbaker.com",
    "https://sticker.fly.dev"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Sticker.Finch

# Do not print debug messages in production
config :logger, level: :info

config :sticker, env: :prod

# sentry
config :sentry,
  dsn:
    "https://62d219ab5cb28f561e96f358b143fbab@o4505880252776448.ingest.sentry.io/4506836912439296",
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  },
  included_environments: [:prod]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
